name: simple_todo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  equatable: ^2.0.7
  intl: ^0.20.2
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  path_provider: ^2.1.6
  path: ^1.9.1
  encrypt: ^5.0.3
  crypto: ^3.0.7
  flutter_secure_storage: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  icons_launcher: ^3.1.0
  change_app_package_name: ^1.5.0
  drift_dev: ^2.24.0
  build_runner: ^2.15.1

icons_launcher:
  image_path: "assets/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    windows:
      enable: true
    macos:
      enable: true

flutter:
  uses-material-design: true

hooks:
  user_defines:
    sqlite3:
      source: source
      path: sqlite3.c



